DROP TABLE ORDINESTORICO;
DROP TABLE APPARTIENE_CATEGORIA;
DROP TABLE DETTAGLIO;
DROP TABLE ORDINE;
DROP TABLE CATEGORIA;
DROP TABLE PRODOTTO;
DROP TABLE INDIRIZZO;
DROP TABLE UTENTE;
DROP SEQUENCE INDIRIZZO_SEQ;
DROP SEQUENCE PRODOTTO_SEQ;
DROP SEQUENCE CATEGORIA_SEQ;

CREATE TABLE UTENTE (
	username VARCHAR2(30) PRIMARY KEY,
	password VARCHAR(16) NOT NULL,
	nome VARCHAR2(30) NOT NULL,
	cognome VARCHAR2(30) NOT NULL,
	data_nascita DATE
);

CREATE TABLE INDIRIZZO(
	id_indirizzo INT PRIMARY KEY,
	via VARCHAR2(40) NOT NULL,
	numero INT NOT NULL,
	citta VARCHAR2(30) NOT NULL,
	cap INTEGER NOT NULL,
	utente VARCHAR2(30) NOT NULL,
	ultimo_indirizzo char(1) check (ultimo_indirizzo in ( 'Y', 'N' )),
	CONSTRAINT FK_US_IND FOREIGN KEY(utente) REFERENCES UTENTE(username) ON DELETE CASCADE
);

CREATE TABLE ORDINE(
	id_ordine INT PRIMARY KEY,
	data_ordine DATE NOT NULL,
	utente VARCHAR2(30) NOT NULL,
	indirizzo INT NOT NULL,
	CONSTRAINT FK_OR_IND FOREIGN KEY(indirizzo) REFERENCES INDIRIZZO(id_indirizzo) ON DELETE CASCADE,
	CONSTRAINT FK_OR_US FOREIGN KEY(utente) REFERENCES UTENTE(username) ON DELETE CASCADE
);

CREATE TABLE PRODOTTO(
    id_prodotto INT PRIMARY KEY,
    prezzo NUMBER(7,2) NOT NULL,
    quantita_disponibile INT NOT NULL,
    nome VARCHAR2(50) NOT NULL,
    descrizione VARCHAR2(100),
    url_immagine VARCHAR2(100)
);

CREATE TABLE DETTAGLIO(
    id_dettaglio INT NOT NULL,
	id_ordine INT NOT NULL,
	id_prodotto INT NOT NULL,
	quantita_acquistata INT NOT NULL,
    prezzo_unitario NUMBER(7,2) NOT NULL,
	CONSTRAINT PK_DETTAGLIO PRIMARY KEY(id_dettaglio,id_ordine,id_prodotto),
	CONSTRAINT FK_DE_ORD FOREIGN KEY (id_ordine) REFERENCES Ordine(id_ordine) ON DELETE CASCADE,
	CONSTRAINT FK_DE_PRO FOREIGN KEY(id_prodotto) REFERENCES Prodotto(id_prodotto) ON DELETE CASCADE 
);

CREATE TABLE CATEGORIA(
	id_categoria INT PRIMARY KEY,
	nome VARCHAR2(30) NOT NULL,
    url_immagine VARCHAR2(100)
);

CREATE TABLE APPARTIENE_CATEGORIA(
	id_prodotto INT NOT NULL,
	id_categoria INT NOT NULL,
	CONSTRAINT pk_app PRIMARY KEY(id_prodotto,id_categoria),
	CONSTRAINT fk_app_pro FOREIGN KEY(id_prodotto) REFERENCES Prodotto(id_prodotto) ON DELETE CASCADE,
	CONSTRAINT fk_app_cat FOREIGN KEY(id_categoria) REFERENCES Categoria(id_categoria) ON DELETE CASCADE
);

CREATE TABLE ORDINESTORICO(
    id_ordine INT NOT NULL,
    id_prodotto INT NOT NULL,
    username VARCHAR2(30) NOT NULL,
    quantita_acquistata INT NOT NULL,
    prezzo_totale NUMBER(7,2) NOT NULL,
    CONSTRAINT PK_OR_STORICO PRIMARY KEY(id_ordine,id_prodotto,username),
    CONSTRAINT fk_sto_pro FOREIGN KEY(id_prodotto) REFERENCES Prodotto(id_prodotto) ON DELETE CASCADE,
    CONSTRAINT fk_sto_user FOREIGN KEY(username) REFERENCES UTENTE(username) ON DELETE CASCADE
);

CREATE SEQUENCE indirizzo_seq
minvalue 0
start with 0
increment by 1
nomaxvalue;

CREATE SEQUENCE PRODOTTO_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE;

CREATE SEQUENCE categoria_seq
minvalue 0
start with 0
increment by 1
nomaxvalue;

CREATE OR REPLACE VIEW LISTA_PRODOTTI AS
SELECT AC.ID_CATEGORIA,P.ID_PRODOTTO,P.PREZZO,P.QUANTITA_DISPONIBILE,P.NOME,P.DESCRIZIONE,P.URL_IMMAGINE
FROM PRODOTTO P
INNER JOIN APPARTIENE_CATEGORIA AC ON P.ID_PRODOTTO=AC.ID_PRODOTTO;